#!/bin/bash
find-utf-8-text()
{
    for i in $1/*
    do
	if [ -f $i ]
	then
	    file $i|grep -i "utf-8 Unicode text"|cut -d ":" -f 1 2>/dev/null
	elif [ -d $i ]
	then 
	    find-utf-8-text $i/*
	fi
    done
}
find-utf-8-text $1
